/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/SystemLowLevelFunction.proto */

#ifndef PROTOBUF_C_proto_2fSystemLowLevelFunction_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fSystemLowLevelFunction_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _Protobuf__SystemLowLevelFunction {
  PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__MIXER_SPEED = 142,
  PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__LAMP_ON = 150,
  PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__LAMP_OFF = 151,
  PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__LAMP_VOLTAGE_ADJUST = 152,
  PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__REFERENCE_MEAS_POS = 153,
  PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__ROTATION_TEACH_IN = 154,
  PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__MEAS_POS_OFFSET = 158,
  PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__TEACH_IN_DONE = 159
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION)
} Protobuf__SystemLowLevelFunction;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    protobuf__system_low_level_function__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fSystemLowLevelFunction_2eproto__INCLUDED */
