/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/SystemLowLevelFunction.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/SystemLowLevelFunction.pb-c.h"
static const ProtobufCEnumValue protobuf__system_low_level_function__enum_values_by_number[8] =
{
  { "MIXER_SPEED", "PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__MIXER_SPEED", 142 },
  { "LAMP_ON", "PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__LAMP_ON", 150 },
  { "LAMP_OFF", "PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__LAMP_OFF", 151 },
  { "LAMP_VOLTAGE_ADJUST", "PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__LAMP_VOLTAGE_ADJUST", 152 },
  { "REFERENCE_MEAS_POS", "PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__REFERENCE_MEAS_POS", 153 },
  { "ROTATION_TEACH_IN", "PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__ROTATION_TEACH_IN", 154 },
  { "MEAS_POS_OFFSET", "PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__MEAS_POS_OFFSET", 158 },
  { "TEACH_IN_DONE", "PROTOBUF__SYSTEM_LOW_LEVEL_FUNCTION__TEACH_IN_DONE", 159 },
};
static const ProtobufCIntRange protobuf__system_low_level_function__value_ranges[] = {
{142, 0},{150, 1},{158, 6},{0, 8}
};
static const ProtobufCEnumValueIndex protobuf__system_low_level_function__enum_values_by_name[8] =
{
  { "LAMP_OFF", 2 },
  { "LAMP_ON", 1 },
  { "LAMP_VOLTAGE_ADJUST", 3 },
  { "MEAS_POS_OFFSET", 6 },
  { "MIXER_SPEED", 0 },
  { "REFERENCE_MEAS_POS", 4 },
  { "ROTATION_TEACH_IN", 5 },
  { "TEACH_IN_DONE", 7 },
};
const ProtobufCEnumDescriptor protobuf__system_low_level_function__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "protobuf.SystemLowLevelFunction",
  "SystemLowLevelFunction",
  "Protobuf__SystemLowLevelFunction",
  "protobuf",
  8,
  protobuf__system_low_level_function__enum_values_by_number,
  8,
  protobuf__system_low_level_function__enum_values_by_name,
  3,
  protobuf__system_low_level_function__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
