// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SystemLowLevelFunction.proto

package pl.cormay.something;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protobuf.SystemLowLevelFunction}
   */
  public enum SystemLowLevelFunction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MIXER_SPEED = 142;</code>
     */
    MIXER_SPEED(142),
    /**
     * <code>LAMP_ON = 150;</code>
     */
    LAMP_ON(150),
    /**
     * <code>LAMP_OFF = 151;</code>
     */
    LAMP_OFF(151),
    /**
     * <code>LAMP_VOLTAGE_ADJUST = 152;</code>
     */
    LAMP_VOLTAGE_ADJUST(152),
    /**
     * <code>REFERENCE_MEAS_POS = 153;</code>
     */
    REFERENCE_MEAS_POS(153),
    /**
     * <code>ROTATION_TEACH_IN = 154;</code>
     */
    ROTATION_TEACH_IN(154),
    /**
     * <code>MEAS_POS_OFFSET = 158;</code>
     */
    MEAS_POS_OFFSET(158),
    /**
     * <code>TEACH_IN_DONE = 159;</code>
     */
    TEACH_IN_DONE(159),
    ;

    /**
     * <code>MIXER_SPEED = 142;</code>
     */
    public static final int MIXER_SPEED_VALUE = 142;
    /**
     * <code>LAMP_ON = 150;</code>
     */
    public static final int LAMP_ON_VALUE = 150;
    /**
     * <code>LAMP_OFF = 151;</code>
     */
    public static final int LAMP_OFF_VALUE = 151;
    /**
     * <code>LAMP_VOLTAGE_ADJUST = 152;</code>
     */
    public static final int LAMP_VOLTAGE_ADJUST_VALUE = 152;
    /**
     * <code>REFERENCE_MEAS_POS = 153;</code>
     */
    public static final int REFERENCE_MEAS_POS_VALUE = 153;
    /**
     * <code>ROTATION_TEACH_IN = 154;</code>
     */
    public static final int ROTATION_TEACH_IN_VALUE = 154;
    /**
     * <code>MEAS_POS_OFFSET = 158;</code>
     */
    public static final int MEAS_POS_OFFSET_VALUE = 158;
    /**
     * <code>TEACH_IN_DONE = 159;</code>
     */
    public static final int TEACH_IN_DONE_VALUE = 159;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SystemLowLevelFunction valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SystemLowLevelFunction forNumber(int value) {
      switch (value) {
        case 142: return MIXER_SPEED;
        case 150: return LAMP_ON;
        case 151: return LAMP_OFF;
        case 152: return LAMP_VOLTAGE_ADJUST;
        case 153: return REFERENCE_MEAS_POS;
        case 154: return ROTATION_TEACH_IN;
        case 158: return MEAS_POS_OFFSET;
        case 159: return TEACH_IN_DONE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SystemLowLevelFunction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SystemLowLevelFunction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SystemLowLevelFunction>() {
            public SystemLowLevelFunction findValueByNumber(int number) {
              return SystemLowLevelFunction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return pl.cormay.something.Protos.getDescriptor().getEnumTypes().get(0);
    }

    private static final SystemLowLevelFunction[] VALUES = values();

    public static SystemLowLevelFunction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SystemLowLevelFunction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.SystemLowLevelFunction)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"proto/SystemLowLevelFunction.proto\022\010pr" +
      "otobuf*\274\001\n\026SystemLowLevelFunction\022\020\n\013MIX" +
      "ER_SPEED\020\216\001\022\014\n\007LAMP_ON\020\226\001\022\r\n\010LAMP_OFF\020\227\001" +
      "\022\030\n\023LAMP_VOLTAGE_ADJUST\020\230\001\022\027\n\022REFERENCE_" +
      "MEAS_POS\020\231\001\022\026\n\021ROTATION_TEACH_IN\020\232\001\022\024\n\017M" +
      "EAS_POS_OFFSET\020\236\001\022\022\n\rTEACH_IN_DONE\020\237\001B\035\n" +
      "\023pl.cormay.somethingB\006Protos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
